### ISSUE TITLE
xsel: Can't open display (run from a VPS)

### ISSUE THREAD

**Issue by yucongo** [skorokithakis/bakeit#4]
Hi.  I came to find `bakeit` from another thread in `pastebinit`.

I ran into some problems when trying to use bakeit from a VPS though. (`bakeit` is not in the paath so I used `bakeit.cli` which appears to run OK.)
```
echo aaa | python3 -m bakeit.cli
Paste URL: https://www.pastery.net/afadqw/
xsel: Can't open display: (null)
: Transport endpoint is not connected
```
I guess maybe it's expected since `xsel` probably requires X display. It would be great if bakeit can be used without X display -- `pastebinit` runs OK without X display.

**Comment by skorokithakis** [comment]
Hm, I'll fix that, thanks. It still runs fine though, no?

**Comment by yucongo** [comment]
No, nothing pasted to https://www.pastery.net/afadqw. I think `bakeit` tried to find `xsel`, failing that it just exited. Refer to the ouput of `echo aaa | python3 -m bakeit.cli`:
```bash
Paste URL: https://www.pastery.net/afadqw/
xsel: Can't open display: (null)
: Transport endpoint is not connected
```

**Comment by skorokithakis** [comment]
I see the paste fine there.

**Comment by yucongo** [comment]
Yeah you are right it works -- I overlooked.

Nevertheless, I submitted a pr (under another account). Please take a look and merge it or not as you see it fit.

**Comment by skorokithakis** [comment]
Great, I'll comment on #5, thanks!
